[package]
name = "cyber-kube-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
tonic = { version = "0.12", features = ["transport", "codegen"] }
prost = "0.13"
async-trait = "0.1"
async-stream = "0.3"
futures-core = "0.3"
futures-util = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tower-http = { version = "0.6", features = ["trace"] }
tokio-stream = "0.1"
k8s-openapi = { version = "0.23", features = ["v1_30"] }
kube = { version = "0.96", features = ["client", "rustls-tls"] }
kube-runtime = "0.96"
wasmtime = "22.0.0"
wasmtime-wasi = "22.0.0"
wat = "1.219.1"

[build-dependencies]
tonic-build = "0.12"
protoc-bin-vendored = "3"

[target.'cfg(target_os = "linux")'.dependencies]
aya = { version = "0.12", features = ["async_tokio"] }
bytes = "1.0"

[dev-dependencies]
tempfile = "3.13"

