FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --silent
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist /app/dist
RUN npm i -g serve --silent
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]

