apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - secrets.yaml
  - ebpf-agent-daemonset.yaml
  - api-go-deployment.yaml
  - api-go-service.yaml
  - engine-deployment.yaml
  - engine-service.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - ml-service-deployment.yaml
  - ml-service-service.yaml
images:
  - name: cyberkube/api-go
    newTag: latest
  - name: cyberkube/engine
    newTag: latest
  - name: cyberkube/dashboard
    newTag: latest
  - name: cyberkube/ml-service
    newTag: latest
  - name: cyberkube/ebpf-agent
    newTag: latest

